import Head from 'next/head';
import { useEffect, Fragment } from 'react';
import { getProviders, signIn } from 'next-auth/react';
import { useRouter } from 'next/router';
import Image from 'next/image';

export default function Home({ providers }: any) {
    return (
    <Fragment>
      <Head>
        <title>Despan</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className='flex flex-col items-center'>
        <h1 className='text-3xl font-bold'>Log In</h1>
        <Image src="/login.png" alt="..." width={250} height={250} />
      </div>
      <div className="flex flex-col justify-evenly items-center w-full">
        {providers && Object.values(providers).map((provider: any) => (
          <div key={provider.name}>
            <div>
              <button onClick={() => signIn(provider.id, { callbackUrl: "/dashboard" })} type="button" 
              className="w-full text-white bg-rose-700 hover:bg-rose-600 focus:ring-4 
              focus:outline-none focus:ring-[#4285F4]/50 font-medium rounded-lg text-sm px-5
              py-2.5 text-center inline-flex items-center dark:focus:ring-[#4285F4]/55 mr-2 mb-2">
                <svg className="w-4 h-4 mr-2 -ml-1" aria-hidden="true" focusable="false" data-prefix="fab" data-icon="google" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 488 512"><path fill="currentColor" d="M488 261.8C488 403.3 391.1 504 248 504 110.8 504 0 393.2 0 256S110.8 8 248 8c66.8 0 123 24.5 166.3 64.9l-67.5 64.9C258.5 52.6 94.3 116.6 94.3 256c0 86.5 69.1 156.6 153.7 156.6 98.2 0 135-70.4 140.8-106.9H248v-85.3h236.1c2.3 12.7 3.9 24.9 3.9 41.4z"></path></svg>
                Sign in with Google
              </button>
            </div>
          </div>
        ))}        
      </div>
    </Fragment>
  )
}

export async function getServerSideProps() {
  const providers = await getProviders();

  return { props: { providers } }
}